spring:
  microservice-name: sample-application-property-for-base-msa-framework
  redis:
    port: 6379
    host: 169.56.171.68
    password: OIpjz8SOJS
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: 30

  session:
    store-type: redis
    redis:
      flush-mode: on_save
      save-mode: always

---
spring:
  microservice-name: ms01
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: on_save
      save-mode: always
    store-type: redis

---
spring:
  microservice-name: ms01
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: ON_SAVE
      save-mode: always
    store-type: redis

---
spring:
  microservice-name: ms01
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: on_save
      save-mode: ALWAYS
    store-type: redis

---
spring:
  microservice-name: ms01
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
      save-mode: always
    store-type: redis

---
spring:
  microservice-name: ms01
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
    timeout: 60
  session:
    redis:
      flush-mode: on_save
      save-mode: always
    store-type: redis

---
spring:
  microservice-name: ms05
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: on_save
      save-mode: always
    store-type: redis

---
spring:
  microservice-name: ms05
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: ON_SAVE
      save-mode: always
    store-type: redis

---
spring:
  microservice-name: ms05
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: on_save
      save-mode: ALWAYS
    store-type: redis

---
spring:
  microservice-name: ms05
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
      save-mode: always
    store-type: redis

---
spring:
  microservice-name: ms05
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
    timeout: 60
  session:
    redis:
      flush-mode: on_save
      save-mode: always
    store-type: redis

---
spring:
  microservice-name: ms06
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: on_save
      save-mode: always
    store-type: redis

---
spring:
  microservice-name: ms06
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: ON_SAVE
      save-mode: always
    store-type: redis

---
spring:
  microservice-name: ms06
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: on_save
      save-mode: ALWAYS
    store-type: redis

---
spring:
  microservice-name: ms06
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
      save-mode: always
    store-type: redis

---
spring:
  microservice-name: ms06
  redis:
    host: 169.56.171.68
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 2
    password: OIpjz8SOJS
    port: 6379
    timeout: 60
  session:
    redis:
      flush-mode: on_save
      save-mode: always
    store-type: redis
