resilience4j.circuitbreaker:
  configs:
    default:
      automaticTransitionFromOpenToHalfOpenEnabled: false
      failureRateThreshold: 50
      minimumNumberOfCalls: 100
      permittedNumberOfCallsInHalfOpenState: 10
      slidingWindowSize: 100
      slidingWindowType: COUNT_BASED
      waitDurationInOpenState: 60000
resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 500ms
resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 3s
server:
  port: 8080
spring:
  application:
    name: ms02
  cloud:
    kubernetes:
      reload:
        mode: event
        period: 5000
