apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        name: microservice
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 15
          periodSeconds: 3
          timeoutSeconds: 2
